version: 2.1
jobs:
    test:
        docker:
            - image: circleci/node:12.16.0
        steps:
            - checkout
            - run: echo "Jest testing"
            - run: yarn install
            - run: yarn test
workflows:
    jest_test:
        jobs:
            - test:
                  filters:
                      branches:
                          only:
                              - develop
